name: Instagram Comment Scraper

on:
  schedule:
    # PEAK HOURS - Every 2 minutes during US business peak times
    # Times are in UTC, adjust for your timezone
    - cron: '*/2 11-14 * * 1-5'     # 6-9 AM ET (peak morning)
    - cron: '*/2 16-17 * * 1-5'     # 12-1 PM ET (lunch peak)
    - cron: '*/2 20-22 * * 1-5'     # 4-6 PM ET (evening peak)
    
    # BUSINESS HOURS - Every 5 minutes during gaps
    - cron: '*/5 14-16,17-20 * * 1-5'  # Business hour gaps
    
    # EVENING - Every 15 minutes
    - cron: '*/15 23-02 * * *'      # 6-9 PM ET evening
    
    # WEEKEND - Reduced frequency
    - cron: '*/10 16-22 * * 6'      # Saturday afternoon
    - cron: '*/30 18-00 * * 0'      # Sunday evening

  # Allow manual testing
  workflow_dispatch:

jobs:
  scrape:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
      
    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '18'
        cache: 'npm'
        
    - name: Install dependencies
      run: npm install
      
    - name: Run Instagram scraper
      env:
        SCRAPINGBEE_API_KEY: ${{ secrets.SCRAPINGBEE_API_KEY }}
        N8N_WEBHOOK_URL: ${{ secrets.N8N_WEBHOOK_URL }}
        INSTAGRAM_POSTS: ${{ secrets.INSTAGRAM_POSTS }}
      run: node instagram-scraper.js
