name: Instagram Comment Scraper

on:
  schedule:
    # PEAK HOURS - Every 2 minutes (1-2 minute response time)
    # Morning Peak: 6-9 AM ET (11-14 UTC)
    - cron: '*/2 11-14 * * 1-5'
    # Lunch Peak: 12-1 PM ET (17 UTC) 
    - cron: '*/2 17 * * 1-5'
    # Evening Peak: 4-6 PM ET (21-23 UTC)
    - cron: '*/2 21-23 * * 1-5'
    
    # BUSINESS HOURS - Every 5 minutes
    # Mid-morning: 9-12 PM ET (14-17 UTC)
    - cron: '*/5 14-16 * * 1-5'
    # Afternoon: 1-4 PM ET (18-21 UTC)
    - cron: '*/5 18-20 * * 1-5'
    
    # EVENING - Every 10 minutes
    # 6-9 PM ET (23-02 UTC next day)
    - cron: '*/10 23-59 * * 1-5'
    - cron: '*/10 0-2 * * 2-6'
    
    # NIGHT - Every 30 minutes
    # 9 PM - 6 AM ET (02-11 UTC)
    - cron: '*/30 3-10 * * *'
    
    # WEEKEND OPTIMIZED
    # Saturday: Every 5 minutes during peak (12-6 PM ET = 17-23 UTC)
    - cron: '*/5 17-23 * * 6'
    # Saturday evening: Every 15 minutes
    - cron: '*/15 0-16,23-59 * * 6'
    # Sunday: Every 15 minutes afternoon (2-8 PM ET = 19-01 UTC)
    - cron: '*/15 19-59 * * 0'
    - cron: '*/15 0-1 * * 1'
    # Sunday other times: Every 30 minutes
    - cron: '*/30 2-18 * * 0'

  # Manual trigger for testing
  workflow_dispatch:

jobs:
  scrape:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
      
    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '18'
        cache: 'npm'
        
    - name: Install dependencies
      run: npm install
      
    - name: Run Instagram scraper
      env:
        SCRAPINGBEE_API_KEY: ${{ secrets.SCRAPINGBEE_API_KEY }}
        N8N_WEBHOOK_URL: ${{ secrets.N8N_WEBHOOK_URL }}
        INSTAGRAM_POSTS: ${{ secrets.INSTAGRAM_POSTS }}
      run: node instagram-scraper.js
